WDPACKAGE_BASIC_KORRA_DOCK_VERSION = 0.01.119
WDPACKAGE_BASIC_KORRA_DOCK_RELEASE_DATE = 2014-12-25
WDPACKAGE_BASIC_KORRA_DOCK_SITE_METHOD = local
WDPACKAGE_BASIC_KORRA_DOCK_SITE = $(TOPDIR)/project/prjPackages/wdcore_korra_dock
WDPACKAGE_BASIC_KORRA_DOCK_DEPENDENCIES = wdpackage_basic

define WDPACKAGE_BASIC_KORRA_DOCK_EXTRACT_CMDS
	cp -Ra $(DL_DIR)/$(WDPACKAGE_BASIC_KORRA_DOCK_SOURCE)/* $(@D)
endef

define WDPACKAGE_BASIC_KORRA_DOCK_INSTALL_TARGET_CMDS
	cp -Raf $(@D)/*  $(TARGET_DIR)
	
	sed -i 's/PMXAC_.*/PMXACKD_'$(WDPACKAGE_BASIC_KORRA_DOCK_VERSION):$(WDPACKAGE_BASIC_KORRA_DOCK_RELEASE_DATE)'/' $(TARGET_DIR)/etc/version.packages
	sed -i 's/PMXACKD_.*/PMXACKD_'$(WDPACKAGE_BASIC_KORRA_DOCK_VERSION):$(WDPACKAGE_BASIC_KORRA_DOCK_RELEASE_DATE)'/' $(TARGET_DIR)/etc/version.packages

endef

$(eval $(generic-package))
