#############################################################
#
# rtkpackage_wpa_supplicant
#
#############################################################

RTKPACKAGE_WPA_SUPPLICANT_VERSION = 2.0
#RTKPACKAGE_WPA_SUPPLICANT_SITE =
RTKPACKAGE_WPA_SUPPLICANT_LICENSE = GPLv2/BSD-3c
RTKPACKAGE_WPA_SUPPLICANT_LICENSE_FILES = README
RTKPACKAGE_WPA_SUPPLICANT_CONFIG = $(RTKPACKAGE_WPA_SUPPLICANT_DIR)/wpa_supplicant/.config
RTKPACKAGE_WPA_SUPPLICANT_SUBDIR = wpa_supplicant
RTKPACKAGE_WPA_SUPPLICANT_DBUS_OLD_SERVICE = fi.epitest.hostap.WPASupplicant
RTKPACKAGE_WPA_SUPPLICANT_DBUS_NEW_SERVICE = fi.w1.wpa_supplicant1
RTKPACKAGE_WPA_SUPPLICANT_CFLAGS = $(TARGET_CFLAGS) -I$(STAGING_DIR)/usr/include/libnl3/
RTKPACKAGE_WPA_SUPPLICANT_LDFLAGS = $(TARGET_LDFLAGS)

ifeq ($(BR2_PACKAGE_LIBNL),y)
	RTKPACKAGE_WPA_SUPPLICANT_DEPENDENCIES += libnl
define RTKPACKAGE_WPA_SUPPLICANT_LIBNL_CONFIG
	echo '' >> $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
	echo 'CONFIG_LIBNL32=y' >>$(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
endef
else
define RTKPACKAGE_WPA_SUPPLICANT_LIBNL_CONFIG
	$(SED) 's/^\(CONFIG_DRIVER_NL80211.*\)/#\1/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
endef
endif

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_EAP),y)
define RTKPACKAGE_WPA_SUPPLICANT_EAP_CONFIG
	$(SED) 's/\(#\)\(CONFIG_EAP_AKA.*\)/\2/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
	$(SED) 's/\(#\)\(CONFIG_EAP_FAST.*\)/\2/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
	$(SED) 's/\(#\)\(CONFIG_EAP_GPSK.*\)/\2/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
	$(SED) 's/\(#\)\(CONFIG_EAP_IKEV2.*\)/\2/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
	$(SED) 's/\(#\)\(CONFIG_EAP_PAX.*\)/\2/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
	$(SED) 's/\(#\)\(CONFIG_EAP_PSK.*\)/\2/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
	$(SED) 's/\(#\)\(CONFIG_EAP_SAKE.*\)/\2/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
	$(SED) 's/\(#\)\(CONFIG_EAP_SIM.*\)/\2/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
	$(SED) 's/\(#\)\(CONFIG_EAP_TNC.*\)/\2/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
	$(SED) 's/\(#\)\(CONFIG_TLSV1.*\)/\2/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
endef
else
define RTKPACKAGE_WPA_SUPPLICANT_EAP_CONFIG
	$(SED) 's/^\(CONFIG_EAP.*\)/#\1/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
endef
endif

#ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_AP_SUPPORT),y)
#define RTKPACKAGE_WPA_SUPPLICANT_AP_CONFIG
#	echo 'CONFIG_AP=y' >>$(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
#endef
#endif

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_WPS),y)
define RTKPACKAGE_WPA_SUPPLICANT_WPS_CONFIG
	$(SED) 's/\(#\)\(CONFIG_WPS.*\)/\2/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
endef
endif

define RTKPACKAGE_WPA_SUPPLICANT_LIBTOMMATH_CONFIG
	$(SED) 's/\(#\)\(CONFIG_INTERNAL_LIBTOMMATH.*\)/\2/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
endef

# Try to use openssl if it's already available
ifeq ($(BR2_PACKAGE_OPENSSL),y)
	RTKPACKAGE_WPA_SUPPLICANT_DEPENDENCIES += openssl
define RTKPACKAGE_WPA_SUPPLICANT_TLS_CONFIG
	$(SED) 's/\(#\)\(CONFIG_TLS=openssl\)/\2/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
	#$(SED) 's/\(#\)\(CONFIG_EAP_PWD.*\)/\2/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
endef
else
define RTKPACKAGE_WPA_SUPPLICANT_TLS_CONFIG
	$(SED) 's/\(#\)\(CONFIG_TLS=\).*/\2internal/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
endef
endif

ifeq ($(BR2_PACKAGE_DBUS),y)
	RTKPACKAGE_WPA_SUPPLICANT_DEPENDENCIES += host-pkgconf dbus
	RTKPACKAGE_WPA_SUPPLICANT_MAKE_ENV = \
		PKG_CONFIG_SYSROOT_DIR="$(STAGING_DIR)"	\
		PKG_CONFIG_PATH="$(STAGING_DIR)/usr/lib/pkgconfig"

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_DBUS_OLD),y)
define RTKPACKAGE_WPA_SUPPLICANT_DBUS_OLD_CONFIG
	$(SED) 's/\(#\)\(CONFIG_CTRL_IFACE_DBUS=\)/\2/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
endef
define RTKPACKAGE_WPA_SUPPLICANT_INSTALL_DBUS_OLD
	$(INSTALL) -D \
	  $(@D)/wpa_supplicant/dbus/$(RTKPACKAGE_WPA_SUPPLICANT_DBUS_OLD_SERVICE).service \
	  $(TARGET_DIR)/usr/share/dbus-1/system-services/$(RTKPACKAGE_WPA_SUPPLICANT_DBUS_OLD_SERVICE).service
endef
endif

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_DBUS_NEW),y)
define RTKPACKAGE_WPA_SUPPLICANT_DBUS_NEW_CONFIG
	$(SED) 's/\(#\)\(CONFIG_CTRL_IFACE_DBUS_NEW=\)/\2/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
endef
define RTKPACKAGE_WPA_SUPPLICANT_INSTALL_DBUS_NEW
	$(INSTALL) -D \
	  $(@D)/wpa_supplicant/dbus/$(RTKPACKAGE_WPA_SUPPLICANT_DBUS_NEW_SERVICE).service \
	  $(TARGET_DIR)/usr/share/dbus-1/system-services/$(RTKPACKAGE_WPA_SUPPLICANT_DBUS_NEW_SERVICE).service
endef
endif

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_DBUS_INTROSPECTION),y)
define RTKPACKAGE_WPA_SUPPLICANT_DBUS_INTROSPECTION_CONFIG
	$(SED) 's/\(#\)\(CONFIG_CTRL_IFACE_DBUS_INTRO=\)/\2/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
endef
endif

define RTKPACKAGE_WPA_SUPPLICANT_DBUS_CONFIG
	$(RTKPACKAGE_WPA_SUPPLICANT_DBUS_OLD_CONFIG)
	$(RTKPACKAGE_WPA_SUPPLICANT_DBUS_NEW_CONFIG)
	$(RTKPACKAGE_WPA_SUPPLICANT_DBUS_INTROSPECTION_CONFIG)
endef

endif

define RTKPACKAGE_WPA_SUPPLICANT_CONFIGURE_CMDS
	#cp $(@D)/wpa_supplicant/defconfig $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
	$(SED) 's/\(#\)\(CONFIG_HS20.*\)/\2/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
	$(SED) 's/\(#\)\(CONFIG_IEEE80211N.*\)/\2/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
	$(SED) 's/\(#\)\(CONFIG_IEEE80211R.*\)/\2/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
	$(SED) 's/\(#\)\(CONFIG_IEEE80211W.*\)/\2/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
	$(SED) 's/\(#\)\(CONFIG_INTERWORKING.*\)/\2/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
	$(SED) 's/\(#\)\(CONFIG_DELAYED_MIC.*\)/\2/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
	$(SED) 's/\(CONFIG_DRIVER_ATMEL\)/#\1/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
	$(SED) 's/\(CONFIG_SMARTCARD\)/#\1/' $(RTKPACKAGE_WPA_SUPPLICANT_CONFIG)
	$(RTKPACKAGE_WPA_SUPPLICANT_LIBTOMMATH_CONFIG)
	$(RTKPACKAGE_WPA_SUPPLICANT_TLS_CONFIG)
	$(RTKPACKAGE_WPA_SUPPLICANT_EAP_CONFIG)
	$(RTKPACKAGE_WPA_SUPPLICANT_WPS_CONFIG)
	$(RTKPACKAGE_WPA_SUPPLICANT_LIBNL_CONFIG)
	$(RTKPACKAGE_WPA_SUPPLICANT_DBUS_CONFIG)
	$(RTKPACKAGE_WPA_SUPPLICANT_AP_CONFIG)
endef

define RTKPACKAGE_WPA_SUPPLICANT_BUILD_CMDS
	$(TARGET_MAKE_ENV) CFLAGS="$(RTKPACKAGE_WPA_SUPPLICANT_CFLAGS)" \
		LDFLAGS="$(TARGET_LDFLAGS)" \
		$(MAKE) CC="$(TARGET_CC)" -C $(@D)/$(RTKPACKAGE_WPA_SUPPLICANT_SUBDIR)
endef

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_CLI),y)
define RTKPACKAGE_WPA_SUPPLICANT_INSTALL_CLI
	$(INSTALL) -m 0755 -D $(@D)/$(RTKPACKAGE_WPA_SUPPLICANT_SUBDIR)/wpa_cli \
		$(TARGET_DIR)/usr/sbin/wpa_cli
endef
endif

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_PASSPHRASE),y)
define RTKPACKAGE_WPA_SUPPLICANT_INSTALL_PASSPHRASE
	$(INSTALL) -m 0755 -D $(@D)/$(RTKPACKAGE_WPA_SUPPLICANT_SUBDIR)/wpa_passphrase \
		$(TARGET_DIR)/usr/sbin/wpa_passphrase
endef
endif

ifeq ($(BR2_PACKAGE_DBUS),y)
define RTKPACKAGE_WPA_SUPPLICANT_INSTALL_DBUS
	$(INSTALL) -D \
	  $(@D)/wpa_supplicant/dbus/dbus-wpa_supplicant.conf \
	  $(TARGET_DIR)/etc/dbus-1/system.d/wpa_supplicant.conf
	$(RTKPACKAGE_WPA_SUPPLICANT_INSTALL_DBUS_OLD)
	$(RTKPACKAGE_WPA_SUPPLICANT_INSTALL_DBUS_NEW)
endef
endif

define RTKPACKAGE_WPA_SUPPLICANT_INSTALL_TARGET_CMDS
	$(INSTALL) -m 0755 -D $(@D)/$(RTKPACKAGE_WPA_SUPPLICANT_SUBDIR)/wpa_supplicant \
		$(TARGET_DIR)/usr/sbin/wpa_supplicant
	$(INSTALL) -m 644 -D package/wpa_supplicant/wpa_supplicant.conf \
		$(TARGET_DIR)/etc/wpa_supplicant.conf
	$(INSTALL) -m 644 -D package/wpa_supplicant/wpa_supplicant.conf \
		$(TARGET_DIR)/etc/wpa2G4_supplicant.conf
	$(RTKPACKAGE_WPA_SUPPLICANT_INSTALL_CLI)
	$(RTKPACKAGE_WPA_SUPPLICANT_INSTALL_PASSPHRASE)
	$(RTKPACKAGE_WPA_SUPPLICANT_INSTALL_DBUS)
endef

$(eval $(generic-package))
