#!/bin/sh
#
# Stolen from RedHat FC5.
#

# Check that smb.conf exists.
[ -f /etc/samba/smb.conf ] || exit 0

# Make directories.
mkdir -p /var/cache/samba
mkdir -p /var/log/samba
mkdir -p /var/lock/subsys
mkdir -p /tmp/lock

RETVAL=0

start() {
	if [ ! -f /etc/samba/secrets.tdb ]; then
		echo -n "Init SMB admin: "
		echo "" | smbpasswd -a -s admin > /dev/null 2>/dev/null
		RETVAL=$?
		echo "done"
	fi

	if [ ! -f /etc/samba/passdb.tdb ]; then
		echo -n "ReCheck SMB admin account: "
		echo "" | smbpasswd -a -s admin > /dev/null 2>/dev/null
		RETVAL=$?
		echo "done"
	fi

	if [ -f /sys/devices/system/cpu/cpu1/online ] && \
		[ "1" = "`cat /sys/devices/system/cpu/cpu1/online`" ]; then
		CPU=2

		if [ -f /proc/irq/54/smp_affinity ]; then
			echo 1 > /proc/irq/54/smp_affinity
		fi
	fi
	TASKSET="/usr/bin/taskset $CPU"

	echo -n "Starting SMB services: "
	${TASKSET} smbd -D > /dev/null 2>/dev/null
	RETVAL=$?
	renice -n 15 -p `pidof smbd` > /dev/null 2>/dev/null
	echo "done"

	echo -n "Starting NMB services: "
	nmbd -D > /dev/null 2>/dev/null
	RETVAL2=$?
	echo "done"

	[ $RETVAL -eq 0 -a $RETVAL2 -eq 0 ] && touch /var/lock/subsys/smb || \
	   RETVAL=1
	return $RETVAL
}	

stop() {
	echo -n "Shutting down SMB services: "
	kill -9 `pidof smbd`
	RETVAL=$?
	rm -f /var/run/smbd.pid
	echo "done"

	echo -n "Shutting down NMB services: "
	kill -9 `pidof nmbd`
	RETVAL2=$?
	rm -f /var/run/nmbd.pid

	[ $RETVAL -eq 0 -a $RETVAL2 -eq 0 ] && rm -f /var/lock/subsys/smb
	echo "done"
	return $RETVAL
}	

restart() {
	stop
	start
}	

reload() {
        echo -n "Reloading smb.conf file: "
	kill -HUP `pidof smbd`
	RETVAL=$?
	echo "done"
	return $RETVAL
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
  	restart
	;;
  reload)
  	reload
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload}"
	exit 1
esac

exit $?
