#!/bin/bash

retry=3

link_Library() {
    isMounted=`mount | grep "/media/sdb1" | wc -l`
    if [ $isMounted -eq 0 ]; then
        echo "No User HDD founded"
	exit 1
    fi

    if [ -d /media/sdb1/.wdcache/.plexmediaserver ]; then
        isLinkToWdcache=`ls -l /usr/local/plexmediaserver/Library | grep "/media/sdb1/.wdcache/.plexmediaserver" | wc -l`
        if [ $isLinkToWdcache -eq 0 ]; then
            rm -f /usr/local/plexmediaserver/Library
            ln -sf /media/sdb1/.wdcache/.plexmediaserver /usr/local/plexmediaserver/Library
        fi
        return
    fi

    if [ -f /media/sdb1/.wdcache/plexmediaserver.img ]; then
        if [ ! -d /data/plexmediaserver ]; then
            mkdir -p /data/plexmediaserver
        fi
        mount -t ext4 -o loop /media/sdb1/.wdcache/plexmediaserver.img /data/plexmediaserver
        sleep 1
        isDataPlexmediaserverMounted=`mount | grep "/data/plexmediaserver" | wc -l`
        while [ $isDataPlexmediaserverMounted -eq 0 ] && [ ${retry} -gt 0 ]
        do
            sleep 3        
            mount -t ext4 -o loop /media/sdb1/.wdcache/plexmediaserver.img /data/plexmediaserver
            isDataPlexmediaserverMounted=`mount | grep "/data/plexmediaserver" | wc -l`
            ((retry --))
        done    
    fi

    if [ $isDataPlexmediaserverMounted -eq 1 ]; then
        if [ ! -L /usr/local/plexmediaserver/Library ]; then
            ln -sf /data/plexmediaserver /usr/local/plexmediaserver/Library
        else
            isLinkToData=`ls -l /usr/local/plexmediaserver/Library | grep "/data/plexmediaserver/" | wc -l`
            if [ $isLinkToData -eq 0 ]; then
                rm -f /usr/local/plexmediaserver/Library
                ln -sf /data/plexmediaserver /usr/local/plexmediaserver/Library
            fi
        fi
    else
        if [ ! -d /media/sdb1/.wdcache/.plexmediaserver ]; then
            mkdir -p /media/sdb1/.wdcache/.plexmediaserver
        fi
        if [ ! -L /usr/local/plexmediaserver/Library ]; then
            if [ ! -d /media/sdb1/.wdcache/.plexmediaserver ]; then
                mkdir -p /media/sdb1/.wdcache/.plexmediaserver
            fi
            mv /usr/local/plexmediaserver/Library/* /media/sdb1/.wdcache/.plexmediaserver/
            rm -Rf /usr/local/plexmediaserver/Library
            ln -sf /media/sdb1/.wdcache/.plexmediaserver /usr/local/plexmediaserver/Library
        else
            isLinkToWdcache=`ls -l /usr/local/plexmediaserver/Library | grep "/media/sdb1/.wdcache/.plexmediaserver" | wc -l`
            if [ $isLinkToWdcache -eq 0 ]; then
                rm -f /usr/local/plexmediaserver/Library
                ln -sf /media/sdb1/.wdcache/.plexmediaserver /usr/local/plexmediaserver/Library
            fi
        fi
    fi

}

unlink_Library() {
    isDataPlexmediaserverMounted=`mount | grep "/data/plexmediaserver" | wc -l`
    if [ $isDataPlexmediaserverMounted -gt 0 ]; then
        fuser -mk /data/plexmediaserver
        sleep 3
        umount /data/plexmediaserver
    fi
}

startme() {
   if [ "`/usr/local/sbin/getServiceStartup.sh twonky`" == "enabled" ]; then
       exit 0
   fi
   if [ "`/usr/local/sbin/getServiceStartup.sh plexmediaserver`" == "disabled" ]; then
       exit 0
   fi
   swapOn=`cat /proc/swaps | wc -l`
   if [ ${swapOn} -eq 1 ]; then
      /sbin/EnableDisableSwap.sh enable 
   fi
   link_Library
   cd /usr/local/plexmediaserver
   ./plexmediaserver.sh start
}

stopme() {
   cd /usr/local/plexmediaserver
   ./plexmediaserver.sh stop
   unlink_Library
}
case $1 in
    start)
        startme
        ;;
    stop)
        stopme
        ;;
    restart)
        stopme;startme
        ;;
    *)
        echo "S80plexmediaserver needs one of the folling options (start|stop|restart)"
esac
